services:
  - type: web
    name: backend
    env: python
    runtime: python-3.11.8
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DATABASE_URL
        fromGroup: reactivate_env
